#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iptraf
Version  : 3.0.0
Release  : 5
URL      : ftp://iptraf.seul.org/pub/iptraf/iptraf-3.0.0.tar.gz
Source0  : ftp://iptraf.seul.org/pub/iptraf/iptraf-3.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: iptraf-bin
BuildRequires : libc6-dev
BuildRequires : pkgconfig(ncurses)
Patch1: iptraf-header-file-location.patch
Patch2: iptraf-makefile.patch

%description
==========================================================================
--------------------------------------------------------------------------
See the RELEASE-NOTES for important update information.
See the INSTALL file for installation instructions.
--------------------------------------------------------------------------

%package bin
Summary: bin components for the iptraf package.
Group: Binaries

%description bin
bin components for the iptraf package.


%prep
%setup -q -n iptraf-3.0.0
%patch1 -p1
%patch2 -p1

%build
make V=1 %{?_smp_mflags} -C src

%install
rm -rf %{buildroot}
cd src
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/bin/iptraf
/bin/rvnamed
